### ISSUE TITLE
Renaming users adds them to operator list (and other)

### ISSUE THREAD

**Issue by ProgramCrafter** [matszpk/simple-irc-server#1]
https://github.com/matszpk/simple-irc-server/blob/64c64b48e468af30c47b0746aae5be96278e3c1f/src/config.rs#L158-L162

Probably user shouldn't always be added to op list. Fortunately, `HashSet::remove` returns `bool` - whether key was in the set, so a fix could be:
```rust
        if let Some(ref mut operators) = self.operators {
            if operators.remove(old_nick) {
                operators.insert(nick.clone());
            }
        }
```

**Comment by matszpk** [comment]
Fixed.
